# Generated by Django 2.2 on 2019-06-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='charging',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='crystal',
            name='uses',
            field=models.ManyToManyField(to='main_app.Use'),
        ),
    ]
