# Generated by Django 2.2 on 2019-06-30 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190630_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='use',
            old_name='description',
            new_name='name',
        ),
    ]
